version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
   mysqldb:
      image: mysql:5.7
      restart: unless-stopped
      #env_file: ./.env
      environment:
         - MYSQL_ROOT_PASSWORD=123456
         - MYSQL_DATABASE=lms
      volumes:
         - ./:/docker-entrypoint-initdb.d
      networks:
         - app-tier             

   app:
      depends_on:
         - mysqldb
      build: ./app
      restart: unless-stopped
      ports:
         - 8090:8080
      environment:
         - DB_HOST=mysqldb
         - DB_USER=root
         - DB_PASSWORD=123456
         - DB_NAME=lms
         - DB_PORT=3306
      stdin_open: true
      tty: true
      networks:
         - app-tier          
